name: Deploy FastAPI Application

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy FastAPI App
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST }} << 'EOF'
          cd /root/instacast-api
          git pull || git clone git@github.com:abehairy/instacast-api.git /root/instacast-api
          python3.9 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          systemctl restart instacast-api.service
        EOF
